# Generated by Django 5.0.6 on 2024-07-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surtidor',
            name='latitud',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='surtidor',
            name='longitud',
            field=models.CharField(max_length=100),
        ),
    ]
